# Config file containing file paths and preprocessing / analysis parameters.

dirs:
  recon_dir: '/d/mjt/9/projects/Dynamo-Analysis/POND-EGNG/subjects_recon'
  mri_dir: '/d/mjt/9/projects/Dynamo-Analysis/POND-EGNG/subjects_mri'
  proc_dir: '/d/mjt/9/projects/Dynamo-Analysis/POND-EGNG/proc_data'
  atlas_dir: '/d/mjt/9/projects/Dynamo-Analysis/POND-EGNG/support_files/atlas'
  model_dir: '/d/mjt/9/projects/Dynamo-Analysis/POND-EGNG/results/6_modes'
  results_dir: '/d/mjt/9/projects/Dynamo-Analysis/POND-EGNG/results'

filenames:
  masterlist_fname: '/d/mjt/9/projects/Dynamo-Analysis/POND-EGNG/support_files/masterlist_complete_19March2026_LB.xlsx'

recon-params:
  n_cores_per_recon: 1

preproc_params:
  filtering:
    lfreq: 1
    hfreq: 45
    notch_freqs: [60, 120, 180]
  resampling_freq: 250

analysis_params:
    dynemo_prep:
        n_embeddings: 15
        n_pca: 90
        standardize: {}
    dynemo_train:
        n_epochs: 20
        n_modes: 6
    selected_training_run: 3  # based on model selection

posthoc:
    orig_mode_order: ['Frontotemporal', 'Background', 'Temporal', 'Visual', 'R Sensorimotor', 'L Sensorimotor']  # based on run3
    new_mode_order: ['Visual', 'L Sensorimotor', 'R Sensorimotor', 'Temporal', 'Frontotemporal', 'Background']
misc:
  exclusion_col: 'Exclude'
  colours: ["#56B4E9", # blue
           "darkgrey", # grey
           "#009E73", # green
           "#E69F00", # orange
           "#9467BD", # purple
           "#CC79A7", # pink
           ]
  groups: 
    - 'CTRL'

